name: Update Data & Deploy Site

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    env:
      NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
      API_NINJAS_KEY: ${{ secrets.API_NINJAS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data update script (Python)
        run: python src/data/api-request.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data $(date -u "+%Y-%m-%d %H:%M:%S")"
          git push
    
